### ISSUE TITLE
Phillips CD-i PCB

### ISSUE THREAD

**Issue by pmgducati** [pmgducati/Blue-Retro-AIO-Units#14]
I do not have this system this PCB is compatible with, please put your findings here.

**Comment by hipsofjw** [comment]
I'm a little confused about this PCB. What are the extra 4 holes for? They don't seem to fit a typical CD-i port. Also, I think you only need one cable since it has the same connector on each end.

**Comment by pmgducati** [comment]
Hi, I am assuming you are referring to these holes:

![image](https://user-images.githubusercontent.com/20894227/173664080-c5d23a28-fe4a-46ac-8ff7-0fbcd4503538.png)

That is for a USB mini connector, according to DarthCloud you need external power for the BlueRetro setup.  The sole purpose of that is to power the unit.

Here is the link to the comments:
https://github.com/darthcloud/BlueRetro/wiki/BlueRetro-Cables-Build-Instructions#cd-i-adapter-cable

**Comment by pmgducati** [comment]
I should add a callout on the PCB for that.  I will get it in the next revision.

**Comment by pmgducati** [comment]
Missed if there too!  Thanks for catching it.  I will update both the PCB and BOM

**Comment by hipsofjw** [comment]
One more thing while I've got you. There's one pad each for RTS and RXD for each port, but there are two RTS and RXD pins in each connector. Do I need to solder both to each pad?

**Comment by pmgducati** [comment]
I don't believe so, it looks like all you need it P1 RTS/RXD from the front and P2 RTS/RXD from the Rear.  Check out the schematic from Darth's repo

https://github.com/darthcloud/BlueRetroHW/blob/master/DIY/CDI.pdf

**Comment by pmgducati** [comment]
Also I updated the CD-i PCB but realized that the library I used had a obsolete part for the mini USB port.  I updated and the foot print did change.  When you buy one for your PCB with the old foot print just make sure to measure the distance from the front row of pins to the GND legs.  the pinout is standard and should fit whatever you find.  Im looking forward to hearing your about your findings on the PCB

**Comment by hipsofjw** [comment]
Went sent the new gerber off to be printed. I'm in China, so it's only a couple of bucks. I'll let you know how it works once I set it up.

Thanks for quick responses and updates!

**Comment by hipsofjw** [comment]
One additional thing: how are you supposed to plug in the micro USB while the PCB is in its case?

**Comment by pmgducati** [comment]
Hey,
I completely missed that when modeling the housing.  I updated it by adding the cutout for power and offsetting the controller cable hole to the side.

I just pushed the commit that includes the changes.

![image](https://user-images.githubusercontent.com/20894227/173872083-3fc1b5ed-dbb0-4cf0-aa41-4492d5bebe23.png)

**Comment by hipsofjw** [comment]
That was fast! No need for a second wiring hole for P2?

**Comment by pmgducati** [comment]
I mirrored the hole for P2:

![image](https://user-images.githubusercontent.com/20894227/173889756-9103e2ce-96bb-4156-a9df-a801701b0cc2.png)

Let me know what you think, you're the expert here ;)

**Comment by pmgducati** [comment]
I pushed it to a branch here:
https://github.com/pmgducati/Blue-Retro-AIO-Units/tree/CD-i-housing-P2-Update

Here is the model if you want to look at it:
https://github.com/pmgducati/Blue-Retro-AIO-Units/blob/CD-i-housing-P2-Update/STL/Aux%20Bottom%20CD-i.STL

if it looks good I will merge it.

**Comment by hipsofjw** [comment]
Looks good to me. Thanks for the update! I'll get one printed up soon.

**Comment by pmgducati** [comment]
Merged!

**Comment by pmgducati** [comment]
@hipsofjw did you finish this?  How is it working?

**Comment by Nekimaliizgrada** [comment]
> I don't believe so, it looks like all you need it P1 RTS/RXD from the front and P2 RTS/RXD from the Rear.  Check out the schematic from Darth's repo
> 
> 
> 
> https://github.com/darthcloud/BlueRetroHW/blob/master/DIY/CDI.pdf
> 
> 

That's it

**Comment by Nekimaliizgrada** [comment]
Phillip ate and drank what his brothers ate and drank. The disrespect of some people. Come on guys.

**Comment by pmgducati** [comment]
@Nekimaliizgrada context?

**Comment by Nekimaliizgrada** [comment]
Climax 😂😂😂😂Sent from my iPhoneOn Nov 19, 2022, at 2:00 PM, pmgducati ***@***.***> wrote:﻿
@Nekimaliizgrada context?
