### ISSUE TITLE
PSX PCB

### ISSUE THREAD

**Issue by pmgducati** [pmgducati/Blue-Retro-AIO-Units#43]
I have successfully tested this with a PS2, but I do not have PSX, please put your findings here.

**Comment by badamsz** [comment]
I have tested on PSX/PSone and it works as long as you connect PIN 3 (7.6v) as PIN 5 (3.5v) provides insufficient power and the ESP won't boot all the way up.

**Comment by pmgducati** [comment]
Thanks for the feedback, I have noted this on the silkscreen of the new rev of the PCB
