### ISSUE TITLE
Filament printing?

### ISSUE THREAD

**Issue by amaiorano** [pmgducati/Blue-Retro-AIO-Units#50]
Hi there!

First of all, awesome project! Thank you for making these, and offering them up for free!

I am interested in making the SNES adapter. I don't have a ton of experience with 3D printing, but when looking at the screenshots of your prints, I get the impression that these STLs won't print all that well with a filament printer. Am I correct? If so, would it be possible to create a simple 1 and 2 hole shell with a generic cover that could be easily printed with a filament printer?

Thanks!

**Comment by pmgducati** [comment]
I have had a few people use my housings on FDM printers, here is an example of one:

![VideoCapture_20220830-115420](https://user-images.githubusercontent.com/20894227/192830473-5b361ba0-7382-42c6-82d3-9feeddef497b.jpg)

I don't think you would have issues printing them.
