### ISSUE TITLE
BOM - Main PCB (ALT WIDE VERSION) - Wrong 1965-ESP32-DEVKITM-1-ND Partno / Link

### ISSUE THREAD

**Issue by stefanpausch** [pmgducati/Blue-Retro-AIO-Units#53]
The linked 1965-ESP32-DEVKITM-1-ND is a 34 Pinout version instead of a required 38 Pinout Version.

Linked is a ESP32 Mini-1

Guess this is the same issue as #49

**Comment by pmgducati** [comment]
The Link has been update.

https://github.com/pmgducati/Blue-Retro-AIO-Units/pull/56
