### ISSUE TITLE
Main PCB _ No Soldermask on anchor / GND point of connector

### ISSUE THREAD

**Issue by stefanpausch** [pmgducati/Blue-Retro-AIO-Units#54]
![blueretro_aio_main_missing_coldermask](https://user-images.githubusercontent.com/184467/200542553-11457d8c-e909-4bf3-bdbf-fc5eb61b82eb.jpg)

Why is the solder mask missing around the anchor points of the connector?

**Comment by pmgducati** [comment]
This is resolved here: https://github.com/pmgducati/Blue-Retro-AIO-Units/pull/55
