### ISSUE TITLE
Blog post on making BlueRetro AIO units

### ISSUE THREAD

**Issue by amaiorano** [pmgducati/Blue-Retro-AIO-Units#70]
Hi, I didn't know how else to reach you, so I hope it's okay that I create an issue for this. I'm a big fan of this project, and I wrote a blog post all about how I made a bunch of these units for different systems. I thought you might enjoy it:

https://amaiorano.io/2023/11/06/blueretro-aio.html

**Comment by pmgducati** [comment]
Thanks for taking time to build and review the adapters.  Do you mind if I put the link on the repo's readme?

**Comment by amaiorano** [comment]
> Thanks for taking time to build and review the adapters. Do you mind if I put the link on the repo's readme?

I would be honored!

**Comment by pmgducati** [comment]
Posted in the Readme.md

**Comment by amaiorano** [comment]
Thanks!
